# coding: utf-8

"""
    Waybiller External API

     **Waybiller** external API is a feature that allows companies to access **Waybiller** data as JSON objects and create **Waybiller** instances out of their own data.  To make integration easier for the companies, external API features mapping support - it is possible to create company specific mappings for object identifiers (such as destination and origin).  These mappings will be used for representing companies data from external API, and for converting the values during creation of **Waybiller** instances (such as transport orders and waybills).  Most of the API responses contain mapped values, that may be null if company doesn't have mapping for this object.  **Waybiller** unique identifiers and values can be accessed through `raw_data` key.  API is HTTPS and JSON based.  # Pagination  By default, results of list endpoints are presented with pages of 30 items.  It is possible to control the page size with `limit` parameter: `/external-api/<some-list-endpoint>/?limit=<number>` where `<number>` is an integer between 1 and 1000. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr, constr
from pywaybiller.openapi_client.models.external_api_vehicle_location_data_raw_data import (
    ExternalAPIVehicleLocationDataRawData,
)


class ExternalAPIVehicleLocationData(BaseModel):
    """
    ExternalAPIVehicleLocationData
    """

    truck_reg_number: Optional[constr(strict=True, min_length=1)] = Field(
        None, description="The registration number of the vehicle."
    )
    waybill_number: Optional[constr(strict=True, min_length=1)] = Field(
        None, description="The waybill number."
    )
    transportation_company_name: Optional[constr(strict=True, min_length=1)] = Field(
        None, description="The name of the transportation company."
    )
    receiver_company_name: Optional[StrictStr] = Field(
        None, description="The name of the receiving company."
    )
    origin_company_name: Optional[StrictStr] = Field(
        None, description="The name of the origin company."
    )
    origin_name: constr(strict=True, max_length=255, min_length=1) = Field(...)
    destination_name: Optional[constr(strict=True, min_length=1)] = Field(
        None, description="The name of the destination."
    )
    raw_data: Optional[ExternalAPIVehicleLocationDataRawData] = None
    vehicle_location_data: Optional[StrictStr] = Field(
        None, description="The vehicle location data."
    )
    __properties = [
        "truck_reg_number",
        "waybill_number",
        "transportation_company_name",
        "receiver_company_name",
        "origin_company_name",
        "origin_name",
        "destination_name",
        "raw_data",
        "vehicle_location_data",
    ]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ExternalAPIVehicleLocationData:
        """Create an instance of ExternalAPIVehicleLocationData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(
            by_alias=True,
            exclude={
                "truck_reg_number",
                "waybill_number",
                "transportation_company_name",
                "receiver_company_name",
                "origin_company_name",
                "destination_name",
                "vehicle_location_data",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of raw_data
        if self.raw_data:
            _dict["raw_data"] = self.raw_data.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ExternalAPIVehicleLocationData:
        """Create an instance of ExternalAPIVehicleLocationData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ExternalAPIVehicleLocationData.parse_obj(obj)

        _obj = ExternalAPIVehicleLocationData.parse_obj(
            {
                "truck_reg_number": obj.get("truck_reg_number"),
                "waybill_number": obj.get("waybill_number"),
                "transportation_company_name": obj.get("transportation_company_name"),
                "receiver_company_name": obj.get("receiver_company_name"),
                "origin_company_name": obj.get("origin_company_name"),
                "origin_name": obj.get("origin_name"),
                "destination_name": obj.get("destination_name"),
                "raw_data": ExternalAPIVehicleLocationDataRawData.from_dict(
                    obj.get("raw_data")
                )
                if obj.get("raw_data") is not None
                else None,
                "vehicle_location_data": obj.get("vehicle_location_data"),
            }
        )
        return _obj
