# coding: utf-8

"""
    Waybiller External API

     **Waybiller** external API is a feature that allows companies to access **Waybiller** data as JSON objects and create **Waybiller** instances out of their own data.  To make integration easier for the companies, external API features mapping support - it is possible to create company specific mappings for object identifiers (such as destination and origin).  These mappings will be used for representing companies data from external API, and for converting the values during creation of **Waybiller** instances (such as transport orders and waybills).  Most of the API responses contain mapped values, that may be null if company doesn't have mapping for this object.  **Waybiller** unique identifiers and values can be accessed through `raw_data` key.  API is HTTPS and JSON based.  # Pagination  By default, results of list endpoints are presented with pages of 30 items.  It is possible to control the page size with `limit` parameter: `/external-api/<some-list-endpoint>/?limit=<number>` where `<number>` is an integer between 1 and 1000. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional, Union
from pydantic import BaseModel, StrictFloat, StrictInt, conint, constr


class ExternalAPITransportOrderUpdate(BaseModel):
    """
    ExternalAPITransportOrderUpdate
    """

    pallets_number: Optional[conint(strict=True, le=32767, ge=0)] = None
    origin_id: Optional[StrictInt] = None
    origin_raw_id: Optional[constr(strict=True, min_length=1)] = None
    origin_name: Optional[constr(strict=True, max_length=255, min_length=1)] = None
    origin_address: Optional[constr(strict=True, max_length=255, min_length=1)] = None
    origin_latitude: Optional[Union[StrictFloat, StrictInt]] = None
    origin_longitude: Optional[Union[StrictFloat, StrictInt]] = None
    shipper_company_name: Optional[
        constr(strict=True, max_length=64, min_length=1)
    ] = None
    shipper_company_reg_code: Optional[
        constr(strict=True, max_length=16, min_length=1)
    ] = None
    destination_id: Optional[StrictInt] = None
    destination_raw_id: Optional[constr(strict=True, min_length=1)] = None
    destination_name: Optional[constr(strict=True, max_length=255, min_length=1)] = None
    destination_address: Optional[
        constr(strict=True, max_length=255, min_length=1)
    ] = None
    destination_latitude: Optional[Union[StrictFloat, StrictInt]] = None
    destination_longitude: Optional[Union[StrictFloat, StrictInt]] = None
    receiver_company_name: Optional[
        constr(strict=True, max_length=64, min_length=1)
    ] = None
    receiver_company_reg_code: Optional[
        constr(strict=True, max_length=16, min_length=1)
    ] = None
    truck_reg_number: Optional[constr(strict=True, max_length=16, min_length=1)] = None
    trailer_reg_number: Optional[constr(strict=True, max_length=16)] = None
    __properties = [
        "pallets_number",
        "origin_id",
        "origin_raw_id",
        "origin_name",
        "origin_address",
        "origin_latitude",
        "origin_longitude",
        "shipper_company_name",
        "shipper_company_reg_code",
        "destination_id",
        "destination_raw_id",
        "destination_name",
        "destination_address",
        "destination_latitude",
        "destination_longitude",
        "receiver_company_name",
        "receiver_company_reg_code",
        "truck_reg_number",
        "trailer_reg_number",
    ]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ExternalAPITransportOrderUpdate:
        """Create an instance of ExternalAPITransportOrderUpdate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # set to None if pallets_number (nullable) is None
        # and __fields_set__ contains the field
        if self.pallets_number is None and "pallets_number" in self.__fields_set__:
            _dict["pallets_number"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ExternalAPITransportOrderUpdate:
        """Create an instance of ExternalAPITransportOrderUpdate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ExternalAPITransportOrderUpdate.parse_obj(obj)

        _obj = ExternalAPITransportOrderUpdate.parse_obj(
            {
                "pallets_number": obj.get("pallets_number"),
                "origin_id": obj.get("origin_id"),
                "origin_raw_id": obj.get("origin_raw_id"),
                "origin_name": obj.get("origin_name"),
                "origin_address": obj.get("origin_address"),
                "origin_latitude": obj.get("origin_latitude"),
                "origin_longitude": obj.get("origin_longitude"),
                "shipper_company_name": obj.get("shipper_company_name"),
                "shipper_company_reg_code": obj.get("shipper_company_reg_code"),
                "destination_id": obj.get("destination_id"),
                "destination_raw_id": obj.get("destination_raw_id"),
                "destination_name": obj.get("destination_name"),
                "destination_address": obj.get("destination_address"),
                "destination_latitude": obj.get("destination_latitude"),
                "destination_longitude": obj.get("destination_longitude"),
                "receiver_company_name": obj.get("receiver_company_name"),
                "receiver_company_reg_code": obj.get("receiver_company_reg_code"),
                "truck_reg_number": obj.get("truck_reg_number"),
                "trailer_reg_number": obj.get("trailer_reg_number"),
            }
        )
        return _obj
