# coding: utf-8

"""
    Waybiller External API

     **Waybiller** external API is a feature that allows companies to access **Waybiller** data as JSON objects and create **Waybiller** instances out of their own data.  To make integration easier for the companies, external API features mapping support - it is possible to create company specific mappings for object identifiers (such as destination and origin).  These mappings will be used for representing companies data from external API, and for converting the values during creation of **Waybiller** instances (such as transport orders and waybills).  Most of the API responses contain mapped values, that may be null if company doesn't have mapping for this object.  **Waybiller** unique identifiers and values can be accessed through `raw_data` key.  API is HTTPS and JSON based.  # Pagination  By default, results of list endpoints are presented with pages of 30 items.  It is possible to control the page size with `limit` parameter: `/external-api/<some-list-endpoint>/?limit=<number>` where `<number>` is an integer between 1 and 1000. 

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt


class ExternalAPILoaderActionLogRawData(BaseModel):
    """
    The IDs of the Waybiller internal objects.  # noqa: E501
    """

    log_id: StrictInt = Field(..., description="The ID of the log.")
    loader_operator_user_id: Optional[StrictInt] = Field(
        ..., description="The ID of the loader operator user."
    )
    origin_id: Optional[StrictInt] = Field(..., description="The ID of the origin.")
    order_id: Optional[StrictInt] = Field(..., description="The ID of the order.")
    vehicle_id: Optional[StrictInt] = Field(..., description="The ID of the vehicle.")
    loader_unit_id: Optional[StrictInt] = Field(
        ..., description="The ID of the loader unit."
    )
    assortment_id: Optional[StrictInt] = Field(
        ..., description="The ID of the assortment."
    )
    subset_id: Optional[StrictInt] = Field(..., description="The ID of the subset.")
    __properties = [
        "log_id",
        "loader_operator_user_id",
        "origin_id",
        "order_id",
        "vehicle_id",
        "loader_unit_id",
        "assortment_id",
        "subset_id",
    ]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ExternalAPILoaderActionLogRawData:
        """Create an instance of ExternalAPILoaderActionLogRawData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # set to None if loader_operator_user_id (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.loader_operator_user_id is None
            and "loader_operator_user_id" in self.__fields_set__
        ):
            _dict["loader_operator_user_id"] = None

        # set to None if origin_id (nullable) is None
        # and __fields_set__ contains the field
        if self.origin_id is None and "origin_id" in self.__fields_set__:
            _dict["origin_id"] = None

        # set to None if order_id (nullable) is None
        # and __fields_set__ contains the field
        if self.order_id is None and "order_id" in self.__fields_set__:
            _dict["order_id"] = None

        # set to None if vehicle_id (nullable) is None
        # and __fields_set__ contains the field
        if self.vehicle_id is None and "vehicle_id" in self.__fields_set__:
            _dict["vehicle_id"] = None

        # set to None if loader_unit_id (nullable) is None
        # and __fields_set__ contains the field
        if self.loader_unit_id is None and "loader_unit_id" in self.__fields_set__:
            _dict["loader_unit_id"] = None

        # set to None if assortment_id (nullable) is None
        # and __fields_set__ contains the field
        if self.assortment_id is None and "assortment_id" in self.__fields_set__:
            _dict["assortment_id"] = None

        # set to None if subset_id (nullable) is None
        # and __fields_set__ contains the field
        if self.subset_id is None and "subset_id" in self.__fields_set__:
            _dict["subset_id"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ExternalAPILoaderActionLogRawData:
        """Create an instance of ExternalAPILoaderActionLogRawData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ExternalAPILoaderActionLogRawData.parse_obj(obj)

        _obj = ExternalAPILoaderActionLogRawData.parse_obj(
            {
                "log_id": obj.get("log_id"),
                "loader_operator_user_id": obj.get("loader_operator_user_id"),
                "origin_id": obj.get("origin_id"),
                "order_id": obj.get("order_id"),
                "vehicle_id": obj.get("vehicle_id"),
                "loader_unit_id": obj.get("loader_unit_id"),
                "assortment_id": obj.get("assortment_id"),
                "subset_id": obj.get("subset_id"),
            }
        )
        return _obj
